//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddressValidation.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sehirler
    {
        public Sehirler()
        {
            this.Ilceler = new HashSet<Ilceler>();
        }
    
        public int SehirId { get; set; }
        public string SehirAdi { get; set; }
        public int TelefonKodu { get; set; }
    
        public virtual ICollection<Ilceler> Ilceler { get; set; }
    }
}
